version: '3'
services:
  backend:
    build: .
    ports:
      - 80:5000
    depends_on:
      - "db"
    command: ["./wait-for-it.sh", "db:3306", "--timeout=60", "--", "python", "main.py"]
    environment:
      DB_HOST: "db"
    stop_signal: SIGINT
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: ilya
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - 3306:3306